# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [3]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

np_height =np.array(height)
np_weight = np.array(weight)

Bmi = np_weight/ (np_height**2) *730
print(Bmi)


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [17]:
# function takes 5 parameters 
# range start , range end , numbers of rows , numbers of column , data type

def ran_ma(rng_start, rng_end , no_row, no_col , d_type ): 
    shp = (no_row, no_col)
    neo = np.random.uniform(rng_start, rng_end, shp).astype(d_type)
    return neo
output = ran_ma(3,9,3,3,'int')
print(output)

[[8 7 6]
 [6 8 6]
 [8 6 8]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [5]:
import csv
import numpy as np






In [20]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs17 = load_data('redsox_2017_hitting.txt')
bs18 = load_data('redsox_2018_hitting.txt')

slg17 = bs17['SLG']
# print(sorted(slg17))
# print(len(slg17))

slg18 =bs18['SLG']
# print(sorted(slg18))
# print(len(slg18))

# claculating Average
Avg_slg_17 = sum(slg17)/ len(slg17)
print(f'Average SLG of 2017:{Avg_slg_17}')

# calculating Average
Avg_slg_18 = sum(slg18)/ len(slg18)
print(f'Average SLG of 2018:{Avg_slg_18}')


print('Based on the average SLG, performance was slightly better in 2017 compared to 2018 ')

Average SLG of 2017:0.39334782374941785
Average SLG of 2018:0.38750000335276125
Based on the average SLG, performance was slightly better in 2017 compared to 2018 
